# Generated by Django 5.0.6 on 2024-05-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_date_ordered_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
