# Generated by Django 5.0.6 on 2024-05-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
