# Generated by Django 5.0.6 on 2024-06-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transmit_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
