# Generated by Django 5.0.6 on 2024-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_client_marked_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
    ]
