# Generated by Django 5.0.6 on 2024-06-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('dispatched', 'Dispatched'), ('intransit', 'In Transit'), ('delivered', 'Delivered')], default='dispatched', max_length=20),
        ),
    ]
